### PR TITLE
Make nested object deletion extensible

### PR DESCRIPTION
**Pull request by kavdev**
It's currently possible to extend create and update functionality by just implementing those methods on the child serializer, but deletion is a bit trickier.

This proposed refactor exposes just the place in the code where deletion takes place so that more functionality can be easily added in user code if desired.

For my particular use case, I want to be able to create events and update inventory any time a nested item is deleted. With this new change, I can simply extend ``perform_nested_delete(pks_to_delete, **kwargs)`` to include my functionality and call super() to ensure the deletion takes place as expected.

As a side effect, this enables users to adopt functionality proposed in #103 and #112 until the PRs are accepted/declined.

### CODE REVIEW

**Comment by kavdev** [comment]
@ruscoder I'm hoping this can get merged quickly, as it's a small refactor that provides a lot of value. Let me know if there are any changes you might want me to make and I'll get on them right away.

**Comment by ruscoder** [comment]
Hi @kavdev! Thanks for the contribution. Seems a good general solution for now.

**Comment by ruscoder** [comment]
I'm not sure that perform_nested_delete is good for public usage due to a lot of arguments, but maybe it can be good for extensibility. Merged

**Comment by ruscoder** [comment]
Available in 0.6.3

**Comment by kavdev** [comment]
@ruscoder fantastic, thanks!

**Pull request merged**
