### PR TITLE
Ps 1573 nested updates

### PR DESCRIPTION
**Pull request by hexvolt**
- support of URLs (HyperlinkIndentityField), UUIDs, pk and ids fields as identifiers of resource added, so the instances can be addressed by either of these fields, no need to expose `pk` anymore in API
- proper support of M2M fields added (supports custom proxy models)
- new `allow_delete_on_update` feature is added. Usage example:

```
class PersonSerializer(NestedCreateMixin, NestedUpdateMixin, serializers.HyperlinkedModelSerializer):
    url = serializers.HyperlinkedIdentityField(...)
    phones = PhoneSerializer(many=True, required=False)
    ...
    class Meta:
        model = models.Person
        allow_delete_on_update = ['phones']
```
means that when PATCHing a Person and the nested field 'phones: []' in the payload doesn't contain an existing phone, the latter (phone instance) will be *deleted* from the database. The default behaviour (without that option set): an existing phone will be just unlinked, the instance itself will be left in the database untouched.

### CODE REVIEW

**Comment by ruscoder** [comment]
@hexvolt The PR became not relevant?

**Comment by hexvolt** [comment]
I will resubmit it shortly

**Comment by Kalpan-Jasani** [comment]
Is there documentation for that? It is not present in the README and I though it would be good to know this upfront rather than digging through git issues.

**Comment by ruscoder** [comment]
@Kalpan-Jasani This PR wasn't merged into the master branch.

**Pull request closed without merging**
