### PR TITLE
Refresh from DB when updating nested object

### PR DESCRIPTION
**Pull request by pcarn**
When I make a PUT or PATCH request on an object that includes changes to a nested model, the response does not include the changes. 
But when I do a GET on the object after that, it shows the changes. It is making the change, but not returning it in the response.

I've confirmed that adding a `refresh_from_db()` in the update serializer fixes this. It responds with the changes I made, and behaves like I'd expect.

Example:
Models:
```python
class Question(BaseModel):
    text = models.CharField(max_length=50)

class Option(BaseModel):
    question = models.ForeignKey(
        "Question", related_name="options", on_delete=models.CASCADE,
    )
    text = models.CharField(max_length=50)
```
Serializers:
```python
class OptionSerializer(DynamicFieldsModelSerializer):
    class Meta:
        model = models.Option
        fields = (
            "id",
            "text",
        )

class QuestionSerializer(WritableNestedModelSerializer):
    options = OptionSerializer(many=True)

    class Meta:
        model = models.Question
        fields = (
            "id",
            "text",
            "options",
        )
```

Before these changes:
```
GET /api/events/questions/cc464c6e-79f8-496d-9aad-d98a7fff11a5/
Response:
{
    "id": "cc464c6e-79f8-496d-9aad-d98a7fff11a5",
    "text": "what is the best cheese?",
    "options": [
        {
            "id": "8cd27b47-129d-4093-8132-0bbcfc17a45a",
            "text": "cheddar"
        },
        {
            "id": "8d53d35c-9694-40d2-9e7c-e1ad83f99bb5",
            "text": "gouda"
        }
    ]
}

PATCH /api/events/questions/cc464c6e-79f8-496d-9aad-d98a7fff11a5/
Body:
{
    "options": [
        {
            "id": "8cd27b47-129d-4093-8132-0bbcfc17a45a",
            "text": "cheddar"
        },
        {
            "id": "8d53d35c-9694-40d2-9e7c-e1ad83f99bb5",
            "text": "gouda"
        },
        {
            "text": "swiss"
        }
    ]
}
Response:
{
    "id": "cc464c6e-79f8-496d-9aad-d98a7fff11a5",
    "text": "what is the best cheese?",
    "options": [
        {
            "id": "8cd27b47-129d-4093-8132-0bbcfc17a45a",
            "text": "cheddar"
        },
        {
            "id": "8d53d35c-9694-40d2-9e7c-e1ad83f99bb5",
            "text": "gouda"
        }
    ]
}

GET /api/events/questions/cc464c6e-79f8-496d-9aad-d98a7fff11a5/
Response:
{
    "id": "cc464c6e-79f8-496d-9aad-d98a7fff11a5",
    "text": "what is the best cheese?",
    "options": [
        {
            "id": "8cd27b47-129d-4093-8132-0bbcfc17a45a",
            "text": "cheddar"
        },
        {
            "id": "8d53d35c-9694-40d2-9e7c-e1ad83f99bb5",
            "text": "gouda"
        },
        {
            "id": "6b33788e-298d-4408-b6ea-dd7dcd1c8232",
            "text": "swiss"
        }
    ]
}

```

After these changes:
```
GET /api/events/questions/cc464c6e-79f8-496d-9aad-d98a7fff11a5/
Response:
{
    "id": "cc464c6e-79f8-496d-9aad-d98a7fff11a5",
    "text": "what is the best cheese?",
    "options": [
        {
            "id": "8cd27b47-129d-4093-8132-0bbcfc17a45a",
            "text": "cheddar"
        },
        {
            "id": "8d53d35c-9694-40d2-9e7c-e1ad83f99bb5",
            "text": "gouda"
        }
    ]
}

PATCH /api/events/questions/cc464c6e-79f8-496d-9aad-d98a7fff11a5/
Body:
{
    "options": [
        {
            "id": "8cd27b47-129d-4093-8132-0bbcfc17a45a",
            "text": "cheddar"
        },
        {
            "id": "8d53d35c-9694-40d2-9e7c-e1ad83f99bb5",
            "text": "gouda"
        },
        {
            "text": "swiss"
        }
    ]
}
Response:
{
    "id": "cc464c6e-79f8-496d-9aad-d98a7fff11a5",
    "text": "what is the best cheese?",
    "options": [
        {
            "id": "8cd27b47-129d-4093-8132-0bbcfc17a45a",
            "text": "cheddar"
        },
        {
            "id": "8d53d35c-9694-40d2-9e7c-e1ad83f99bb5",
            "text": "gouda"
        },
        {
            "id": "6b33788e-298d-4408-b6ea-dd7dcd1c8232",
            "text": "swiss"
        }
    ]
}

GET /api/events/questions/cc464c6e-79f8-496d-9aad-d98a7fff11a5/
Response:
{
    "id": "cc464c6e-79f8-496d-9aad-d98a7fff11a5",
    "text": "what is the best cheese?",
    "options": [
        {
            "id": "8cd27b47-129d-4093-8132-0bbcfc17a45a",
            "text": "cheddar"
        },
        {
            "id": "8d53d35c-9694-40d2-9e7c-e1ad83f99bb5",
            "text": "gouda"
        },
        {
            "id": "6b33788e-298d-4408-b6ea-dd7dcd1c8232",
            "text": "swiss"
        }
    ]
}

```

### CODE REVIEW

**Comment by pcarn** [comment]
I can use a workaround by adding this to `QuestionSerializer`:

```python
     def update(self, instance, validated_data):
         instance.refresh_from_db()
         return super().update(instance, validated_data)
```

But this seems like something that should be default behavior, and it would be nice to not need a workaround.

**Comment by ruscoder** [comment]
Hello @pcarn! Thanks for your contribution. Could you please add tests covering your case (tests that fail without this PR)?

**Comment by ruscoder** [comment]
It seems like a good improvement, I'm ready to merge it to the master.

**Comment by pcarn** [comment]
@ruscoder Thanks! Added tests

**Comment by pcarn** [comment]
@ruscoder Can this be merged so I can start using it?

**Comment by ruscoder** [comment]
@pcarn Thanks! I've just published version 0.6.2 which includes your fix.

**Pull request merged**
