### PR TITLE
Known problems with solutions in README file modified with a fix for …

### PR DESCRIPTION
**Pull request by xalien10**
Known problems with solutions in README file modified with a fix for formdata update of nested fields via PUT or PATCH request

### CODE REVIEW

**Comment by ir4y** [comment]
Thank you for your contribution @xalien10 
There are two small notes.

1. Could you please leave the only minimum necessary set of fields in the example? There are a lot of fields that don't need to represent the issue and it confuses.
2. Could you please provide an example of a working serializer or at least some part of it? You describe the technique, it is cool and should be in the README, but also it would be nice to provide more context where this code and be user, what serializer's controller's methods need to be override?

**Comment by xalien10** [comment]
@ir4y I'll do that. Thank you for your feedback

**Comment by xalien10** [comment]
@ir4y I've updated the PR with more concrete example. Please take a look when you have some time for it.

**Comment by ir4y** [comment]
@xalien10 
Sorry for the long reply. It seems that everything is almost done.
May I kindly ask you to add a test that demonstrates this behavior?
I think it will provide an even better experience than just a code snippet.

**Comment by ir4y** [comment]
Ok, I am merging the documentation. If somebody face some issue with examples we will revisit the topic about tests.
Thank you @xalien10

**Comment by xalien10** [comment]
@ir4y I'm extremely sorry that I couldn't reply you back. Currently, I'm loaded heavily so couldn't write appropriate tests for the solution. If I can manage some time I'll definitely make a PR on that including the tests you asked for.

**Comment by auvipy** [comment]
> @ir4y I'm extremely sorry that I couldn't reply you back. Currently, I'm loaded heavily so couldn't write appropriate tests for the solution. If I can manage some time I'll definitely make a PR on that including the tests you asked for.

good job bro

**Pull request merged**
