### PR TITLE
Drop end-of-life Django versions, add Django 2.2 and 3.0, and Python 3.8

### LINKED ISSUE #87: Fix CI build for Django 2.2
It seems that everything is OK with tests for 2.2 but the build fails on the CI.

Django 2.2 was temporarily removed from travis/tox https://github.com/beda-software/drf-writable-nested/commit/f06df1a2dcac222f519bb368da273150036b8323
Failing build:
https://travis-ci.org/beda-software/drf-writable-nested/jobs/547545561

### LINKED ISSUE #109: Drop Python 2.7
Django and DRF have both dropped Python 2.7. `drf-writable-nested` should consider following suit.

Currently, we must use `pytest` at `<5` in `requirements.txt` to support Python 2.7.

### PR DESCRIPTION
**Pull request by johnthagen**
- Drop end-of-life Django versions: 1.9, 1.10, 1.11, 2.0, 2.1
- Add new Django versions: 2.2, 3.0
- Drop DRF versions: 3.5-3.7 (2016-2017 era)
- Add new DRF versions: 3.10, 3.11

- Drop end-of-life Python versions: 2.7
- Add new Python versions: 3.8

- Fix Django 4.0 `DeprecationWarning` (borrowed from #107).
- Bump `pytest` versions in `requirements.txt` to remove several `DeprecationWarning`s.
- Enabling all CI runs

For a list of currently supported Django versions: https://www.djangoproject.com/download/

Closes #87
Closes #109

### CODE REVIEW

**Comment by johnthagen** [comment]
Build results here: https://travis-ci.org/github/beda-software/drf-writable-nested/builds/669927793

Django 2.2 and 3.0 falling

@auviper any ideas?

**Comment by johnthagen** [comment]
@ruscoder I believe the settings in this repo need to be updated so that Travis CI is properly reported.

Perhaps: https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by johnthagen** [comment]
Potential reason for failure on Django >=2.2: https://stackoverflow.com/a/57576705

**Comment by johnthagen** [comment]
Perhaps the [`tests/models.py`](https://github.com/beda-software/drf-writable-nested/blob/master/tests/models.py) needs migrations? I'm not familiar with migrations for test `Model`s.

**Comment by johnthagen** [comment]
@ruscoder For my repositories to properly sync with Travis CI, I needed to [migrate my repositories from travis-ci.**org** to travis-ci.**com**](https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798?u=johnthagen)

**Comment by johnthagen** [comment]
Latest build results: https://travis-ci.org/github/beda-software/drf-writable-nested/builds/670932950

**Comment by ruscoder** [comment]
@johnthagen Thanks for the contribution. I'll review it soon

**Comment by johnthagen** [comment]
@ruscoder Great! 

I'm still at a loss for why Django 2.2-3.0 it fails on CI. Perhaps a different version of SQLite (CPython on Windows probably bundles the latest version?)? If we could find a Django expert, they could probably shed some light.

Here is the result when I run locally on Windows (everything passes that I have Python installed for):

```
=========================================== 33 passed in 1.43 seconds ============================================
____________________________________________________ summary _____________________________________________________
SKIPPED:  py27-dj111-drf35: InterpreterNotFound: python2.7
SKIPPED:  py27-dj111-drf36: InterpreterNotFound: python2.7
SKIPPED:  py27-dj111-drf37: InterpreterNotFound: python2.7
SKIPPED:  py35-dj111-drf35: InterpreterNotFound: python3.5
SKIPPED:  py35-dj111-drf36: InterpreterNotFound: python3.5
SKIPPED:  py35-dj111-drf37: InterpreterNotFound: python3.5
SKIPPED:  py36-dj111-drf35: InterpreterNotFound: python3.6
SKIPPED:  py36-dj111-drf36: InterpreterNotFound: python3.6
SKIPPED:  py36-dj111-drf37: InterpreterNotFound: python3.6
  py37-dj111-drf35: commands succeeded
  py37-dj111-drf36: commands succeeded
  py37-dj111-drf37: commands succeeded
SKIPPED:  py35-dj21-drf37: InterpreterNotFound: python3.5
SKIPPED:  py35-dj21-drf38: InterpreterNotFound: python3.5
SKIPPED:  py35-dj21-drf39: InterpreterNotFound: python3.5
SKIPPED:  py35-dj21-drf310: InterpreterNotFound: python3.5
SKIPPED:  py35-dj21-drf311: InterpreterNotFound: python3.5
SKIPPED:  py35-dj22-drf37: InterpreterNotFound: python3.5
SKIPPED:  py35-dj22-drf38: InterpreterNotFound: python3.5
SKIPPED:  py35-dj22-drf39: InterpreterNotFound: python3.5
SKIPPED:  py35-dj22-drf310: InterpreterNotFound: python3.5
SKIPPED:  py35-dj22-drf311: InterpreterNotFound: python3.5
SKIPPED:  py36-dj21-drf37: InterpreterNotFound: python3.6
SKIPPED:  py36-dj21-drf38: InterpreterNotFound: python3.6
SKIPPED:  py36-dj21-drf39: InterpreterNotFound: python3.6
SKIPPED:  py36-dj21-drf310: InterpreterNotFound: python3.6
SKIPPED:  py36-dj21-drf311: InterpreterNotFound: python3.6
SKIPPED:  py36-dj22-drf37: InterpreterNotFound: python3.6
SKIPPED:  py36-dj22-drf38: InterpreterNotFound: python3.6
SKIPPED:  py36-dj22-drf39: InterpreterNotFound: python3.6
SKIPPED:  py36-dj22-drf310: InterpreterNotFound: python3.6
SKIPPED:  py36-dj22-drf311: InterpreterNotFound: python3.6
  py37-dj21-drf37: commands succeeded
  py37-dj21-drf38: commands succeeded
  py37-dj21-drf39: commands succeeded
  py37-dj21-drf310: commands succeeded
  py37-dj21-drf311: commands succeeded
  py37-dj22-drf37: commands succeeded
  py37-dj22-drf38: commands succeeded
  py37-dj22-drf39: commands succeeded
  py37-dj22-drf310: commands succeeded
  py37-dj22-drf311: commands succeeded
  py38-dj21-drf37: commands succeeded
  py38-dj21-drf38: commands succeeded
  py38-dj21-drf39: commands succeeded
  py38-dj21-drf310: commands succeeded
  py38-dj21-drf311: commands succeeded
  py38-dj22-drf37: commands succeeded
  py38-dj22-drf38: commands succeeded
  py38-dj22-drf39: commands succeeded
  py38-dj22-drf310: commands succeeded
  py38-dj22-drf311: commands succeeded
SKIPPED:  py36-dj30-drf310: InterpreterNotFound: python3.6
SKIPPED:  py36-dj30-drf311: InterpreterNotFound: python3.6
  py37-dj30-drf310: commands succeeded
  py37-dj30-drf311: commands succeeded
  py38-dj30-drf310: commands succeeded
  py38-dj30-drf311: commands succeeded
  congratulations :)
```

**Comment by johnthagen** [comment]
Latest build results: https://travis-ci.org/github/beda-software/drf-writable-nested/builds/671278091

The only currently supported versions of Django are 2.2 and 3.0, and unfortunately those are the ones that fail on CI (but pass for me locally).

Sorry to ping you @rpkilby, but as someone involved with DRF, I was wondering if you happened to have a moment to look over the `drf-writable-nested` failures in the link above and possibly had any ideas on why `drf-writable-nested` tests have started failing on CI as of Django 2.2.

Perhaps related to https://stackoverflow.com/a/57576705?

```
==================================== ERRORS ====================================
_ ERROR at setup of NestedValidationTestCase.test_save_direct_foreign_key_validation_error _
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/utils.py:82: in _execute
    return self.cursor.execute(sql)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py:381: in execute
    return Database.Cursor.execute(self, query)
E   sqlite3.OperationalError: no such table: django_content_type
The above exception was the direct cause of the following exception:
.tox/py35-dj22-drf37/lib/python3.5/site-packages/pytest_django/plugin.py:534: in _django_setup_unittest
    request.getfixturevalue("django_db_setup")
.tox/py35-dj22-drf37/lib/python3.5/site-packages/pytest_django/fixtures.py:108: in django_db_setup
    **setup_databases_args
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/test/utils.py:174: in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/base/creation.py:72: in create_test_db
    run_syncdb=True,
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/core/management/__init__.py:148: in call_command
  return command.execute(*args, **defaults)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/core/management/base.py:364: in execute
    output = self.handle(*args, **options)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/core/management/base.py:83: in wrapped
    res = handle_func(*args, **kwargs)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/core/management/commands/migrate.py:203: in handle
    self.sync_apps(connection, executor.loader.unmigrated_apps)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/core/management/commands/migrate.py:340: in sync_apps
    if self.verbosity >= 1:
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/sqlite3/schema.py:34: in __exit__
    self.connection.check_constraints()
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py:341: in check_constraints
    column_name, referenced_column_name,
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/utils.py:67: in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/utils.py:76: in _execute_with_wrappers
    return executor(sql, params, many, context)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/utils.py:82: in _execute
    return self.cursor.execute(sql)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/utils.py:89: in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/utils.py:82: in _execute
    return self.cursor.execute(sql)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py:381: in execute
    return Database.Cursor.execute(self, query)
E   django.db.utils.OperationalError: no such table: django_content_type
_ ERROR at setup of NestedValidationTestCase.test_save_direct_many_to_many_validation_error _
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/utils.py:82: in _execute
    return self.cursor.execute(sql)
.tox/py35-dj22-drf37/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py:381: in execute
    return Database.Cursor.execute(self, query)
E   sqlite3.OperationalError: no such table: django_content_type
```

**Comment by rpkilby** [comment]
@johnthagen The migrations issue sounds correct. From the 2.2 release notes:

> Tests will fail on SQLite if apps without migrations have relations to apps with migrations. This has been a documented restriction since migrations were added in Django 1.7, but it fails more reliably now. You’ll see tests failing with errors like **no such table: \<app_label\>_\<model\>**. This was observed with several third-party apps that had models in tests without migrations. You must add migrations for such models.

And what version of sqlite are you running locally?

> The minimum supported version of SQLite is increased from 3.7.15 to 3.8.3.

----

Anyway, I would generate the migrations and add them to the PR. iirc, you need to add the `<app>/migrations/__init__.py` file before Django will generate migrations.

**Comment by johnthagen** [comment]
@rpkilby Thanks for the note.

> And what version of sqlite are you running locally?

Locally I'm running this configuration on Windows and it's working:

```
>python --version
Python 3.7.5

>>> import sqlite3
>>> sqlite3.version
'2.6.0'
>>> sqlite3.sqlite_version
'3.28.0'
```

On CI, where it's failing it [looks to be running sqlite 3.11.0, as it's Xenial](https://launchpad.net/ubuntu/xenial/+package/sqlite3).

**Comment by johnthagen** [comment]
@rpkilby 

> Anyway, I would generate the migrations and add them to the PR. iirc, you need to add the <app>/migrations/__init__.py file before Django will generate migrations.

I guess what I'm confused about is that `drf-writable-nested` isn't actually a Django app, so it doesn't have a `manage.py`, an `app` folder, etc. It just has `tests/models.py`. 

Even DRF itself has [`tests/models.py`](https://github.com/encode/django-rest-framework/blob/master/tests/models.py) that don't seem to have corresponding migrations.

I'm not sure where I'm supposed to put/make migrations for a library that isn't a real Django app, if that makes sense?

**Comment by rpkilby** [comment]
> I guess what I'm confused about is that `drf-writable-nested` isn't actually a Django app

Right, it's not complaining about `drf-writable-nested`, it's complaining about the test models. If you look at the conftest module, `tests` is included in the `INSTALLED_APPS`.

> Even DRF itself has `tests/models.py`

Yes - the issue only occurs if your app has FKs to another app with migrations. See:

> Tests will fail on SQLite if apps without migrations have relations to apps with migrations. 

DRF's test models don't have FKs to external app models, so it doesn't have this issue. 

> I'm not sure where I'm supposed to put/make migrations for a library that isn't a real Django app, if that makes sense?

From Django's perspective, `tests` is a real app, so you'd need to add migrations to `tests/migrations`. That said, this will be a bit annoying, since the settings are configured through `conftest` and not a traditional settings file, so you'll need to create a temp copy of the settings as an actual settings module. And since there's no `manage.py` module, you'll need to call something like `django-admin makemigrations tests --settings=path.to.temp.settings`

**Comment by johnthagen** [comment]
@rpkilby Thanks, that worked! See the [green build results](https://travis-ci.org/github/beda-software/drf-writable-nested/builds/673236854).

@ruscoder This PR is ready for final review.

- [ ] Please squash the commits when you merge
- [ ] I suggest [migrating the repository from travis-ci.**org** to travis-ci.**com**](https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798?u=johnthagen) to get build statuses to appear in PRs
- [ ] Please release `drf-writable-nested` `0.6.0`, which will address the `DeprecationWarning` fixed in this PR

Note that I left the scaffolding in place to `manage.py makemigrations` as if the test `Model`s ever change, the migrations will need to be refreshed.

**Comment by rpkilby** [comment]
btw, you should be able to delete the `settings.configure()` call in conftest and set the `DJANGO_SETTINGS_MODULE` path in the pytest ini conf to load the new settings module.

https://pytest-django.readthedocs.io/en/latest/configuring_django.html#pytest-ini-settings

**Comment by johnthagen** [comment]
@rpkilby Thanks! That made everything much cleaner.

@ruscoder This should be [good to go now](https://github.com/beda-software/drf-writable-nested/pull/108#issuecomment-611820161). [Build results green](https://travis-ci.org/github/beda-software/drf-writable-nested/builds/673615699).

**Comment by ruscoder** [comment]
Great work, thanks!

**Comment by ruscoder** [comment]
drf-writable-nested 0.6.0 is available on PyPI

**Pull request merged**
